
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://anheledir.net"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: ""

# Google tracking id to track your visitors

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Gordon Breuer"
title: "{ anheledir.NET }"
description: "Gordon Breuer's blog about IT-Architecture, Developing and mainly Microsoft Technologies. Opinions expressed are mine."
keywords: "gordon, breuer, windows, uwp, windows phone, windows mobile, windows 10, universal apps, xaml, architect, media design, microsoft, dotnet, mobile, augmented reality, consultant, developer"
favicon: "/img/favicon.ico"
404-img: "/img/labtocat.png"

################
# Header layout #
################

black-favicon: "/img/black-lab-glass.ico"

background-img: "../img/intro-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 5
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "The lower you fall, the higher you'll fly."
  - text: "Where’s your will to be weird?"

me-img: "/img/jetpacktocat.png"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: "Anheledir"

syntax-highlight: True

############
# Timeline #
############

events:
#  - image: "/img/timeline/spidertocat.png"
#    date: "September 2013 - Today"
#    description: "Saving the neighborhood!"
#  - image: "/img/timeline/baracktocat.jpg"
#    date: "September 2007 - August 2013"
#    description: "Started coding"

# First image of the Timeline

timeline-img: "/img/timeline/default.png"

###########
# Contact #
###########

email: "mail@gordon-breuer.de"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://facebook.com/gordon.breuer"
  - title: "twitter"
    url: "https://twitter.com/anheledir"
  - title: "github"
    url: "https://github.com/Anheledir"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

404-img: "/img/labtocat.png"

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Custom Emoji image-path
 emoji-images-path: 'img/emoji' 
 
 
# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
