
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://gordon-breuer.de"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: ""

# Google tracking id to track your visitors

google-tracking-id: ""

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: False

#############
# HTML Head #
#############

lang: "en"
author: "Gordon Breuer"
title: "{ anheledir.NET }"
description: "Gordon Breuer's blog about IT-Architecture, Developing and mainly Microsoft Technologies. Opinions expressed are mine."
keywords: "gordon, breuer, windows, uwp, windows phone, windows mobile, windows 10, universal apps, xaml, architect, media design, microsoft, dotnet, mobile, augmented reality, consultant, developer"
favicon: "/img/favicon.ico"
404-img: "/img/labtocat.png"

################
# Header layout #
################

black-favicon: "/img/black-lab-glass.ico"

background-img: "../img/intro-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: False
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 5
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "Where’s your will to be weird?"
  - text: "Arguing with an Engineer is a lot like wrestling in the mud with a pig:<br />After a couple of hours you realize the pig likes it."
  - text: "People ask me, &quot;Why do you drink diet soda?&quot;<br />So I can eat regular cake!"
  - text: "Said Schrodinger’s cat with a smile:<br />&quot;I’ll be in the box with a vial.<br />With the poison I’ll be<br />Quantum tangled you see,<br />Thus alive and dead both all the while.&quot;"
  - text: "Five card stud, nothing wild. And the sky’s the limit"
  - text: "Invention, my dear friends, is<ul><li>93% perspiration,</li><li>6% electricity,</li><li>4% evaporation,</li><li>and 2% butterscotch ripple.</li></ul>"
  - text: "Try not. Do, or do not. There is no try."
  - text: "If we knew what it was we were doing, it would not be called research, would it?"
  - text: "Shall we play a game?"
  - text: "No-one has ever called me a cool dude.<br/>I’m somewhere between geek and normal."
  - text: "People who think they know everything are a great annoyance to those of us who do."
  - text: "We are all here on earth to help others;<br />what on earth the others are here for I don’t know."
  - text: "I’m sorry, if you were right, I’d agree with you."
  - text: "There cannot be a crisis next week.<br/>My schedule is already full."
  - text: "If you’re going to do something tonight that you’ll be sorry for tomorrow morning, sleep late."
  - text: "My book smell better than your tablet."
  - text: "I’m not a nerd. I’m just smarter than you."
  - text: "At the end of each day, life should ask us: &quot;Do you want to save the changes?&quot;"

me-img: "/img/portrait-sunglasses.png"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: "Anheledir"

syntax-highlight: True

############
# Timeline #
############

events:
  # - image: "/img/timeline/baracktocat.jpg"
  #   date: "Mai 2012 - Today"
  #   description: "Working at msg systems AG as Consultant and Software Engineer"
  # - image: "/img/timeline/spidertocat.png"
  #   date: "Juli 2009 - April 2012"
  #   description: "Working at DMDE GmbH as Technology Producer"

# First image of the Timeline

timeline-img: "/img/timeline/default.png"

###########
# Contact #
###########

email: "mail@gordon-breuer.de"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://facebook.com/gordon.breuer"
  - title: "twitter"
    url: "https://twitter.com/anheledir"
  - title: "skype"
    url: "skype:Anheledir"
  - title: "xing"
    url: "https://www.xing.com/profile/Gordon_Breuer"
  - title: "linkedin"
    url: "https://de.linkedin.com/in/gordonbreuer"
  - title: "github"
    url: "https://github.com/Anheledir"
  - title: "stack-overflow"
    url: "http://stackoverflow.com/users/5703/anheledir"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

404-img: "/img/labtocat.png"

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Imprint: 'imprint'
  Privacy: 'privacy'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts", "Tutorial"]

# Pagination path

paginate_path: "blog/page:num/"


# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jekyll-gist
  - emoji_for_jekyll
